- src/_includes/cards/development-activity.html
- src/cards.html
Some typos I found when working on [angular-tabler](https://github.com/beeman/angular-tabler)
> Fix some typos

- README.md
Changed the language of your paragraph to be more concise. Added <hr> in between sections to make your sections more readable.
> Update README for content / readability 

- README.md
> Revert "Update README for content / readability "

- .gitignore
- composer.json
Add composer.json and add /vendor/ to .gitignore
> Support composer

- README.md
Rewrote a few sentences to remove unnecessary words. Fixed grammar issues.
> Changed a few sentence structures

- README.md
This PR adds an invite link to the Slack community.
Please tell me if you'd like to see the link at another place.
> Add link to slack invite page

- src/_includes/cards/form-all-elements.html
I started on #37 
I did it without adding any new JavaScript or CSS, but maybe you want to make it styled a little nicer and hide the input if "..." isn't selected.
> Add inclusive gender input options

- README.md
First open source contribution! Hope this is useful!
> Fixed a few grammatical errors in the README

- src/assets/scss/dashboard/_progress.scss
"dimmer-content" opacity too much.
> "dimmer-content" opacity too much.

- src/_includes/header.html
fixes #112 
First ever OS contribution
> Class .text-muted-dark not needed on dropdown

- src/_includes/cards/finance.html
> Fixing typo

- src/maps.html
> Improve the responsive view of Maps page

- README.md
I think README looks nice again!
> Fix Screenshot

- .gitignore
- build/browsersync.js
- build/generate-font-codepoints.js
- build/rollup.config.js
- js/app/charts.js
- js/tabler.js
- package.json
I'm pretty sure that you had minification on, but I've found out that it's not automatic on `build` command so I've added it. Also, added basic bundlesize config based on current size :)
> Eslint and basic minification (?)

- src/_includes/cards/table-users.html
> Update settings and user icons

- src/assets/scss/_variables.scss
- src/assets/scss/dashboard/_browser.scss
- src/assets/scss/dashboard/_flag.scss
- src/assets/scss/dashboard/_payments.scss
- src/assets/scss/dashboard/_utilities.scss
- src/assets/scss/dashboard/fonts/_feather.scss
Add two variables, `$tabler-path-fonts`, and `$tabler-path-images` to allow respective customization of font and image paths.
> feat: add image and font path variables

- README.md
Maybe this is obvious to other people but as someone who doesn't do much front-end development, it took me some time to realize that this project uses Liquid. Though not a big change, I think this edit makes the docs more honest and will save others time.
> mention Liquid so new users have correct expectations

- pages/_docs/buttons.md
> buttons docs fulfilled

- README.md
> Fix: contributors link

- scss/vendor/_selectize.scss
> Fixed selectize wrap

- src/pages/_data/menu.yml
- src/pages/_docs/skeleton.md
- src/pages/_includes/cards/skeleton/card-1.html
- src/pages/_includes/cards/skeleton/card-2.html
- src/pages/_includes/cards/skeleton/card-3.html
- src/pages/_includes/cards/skeleton/card-4.html
- src/pages/_includes/cards/skeleton/card-5.html
- src/pages/_includes/cards/skeleton/card-6.html
- src/pages/_includes/example.html
- src/pages/skeleton.html
- src/scss/_tabler-core.scss
- src/scss/demo/_examples.scss
- src/scss/ui/_avatars.scss
- src/scss/ui/_cards.scss
- src/scss/ui/_grid.scss
- src/scss/ui/_lists.scss
- src/scss/ui/_skeleton.scss
New `skeleton` component. Inspired by https://material-ui.com/components/skeleton/
Skeleton elements:
- line
- heading
- image
- avatar
> Skeleton component

- src/pages/_data/menu.yml
- src/pages/_includes/forms/form-elements-6.html
- src/pages/_includes/layout/navbar-menu.html
- src/scss/_variables.scss
- src/scss/ui/_dropdowns.scss
Better way to group menu items in columns
> dropdown menu columns rebuild

- README.md
- package.json
New package location: https://www.npmjs.com/package/@tabler/core .
> Package rename

- src/js/tabler.js
> Update tabler.js for tooltip

- src/pages/_includes/parts/form/fieldset.html
- src/scss/ui/forms/_form-check.scss
Changes:
- Added asterisk sign with `$red` color to checkbox label (`.form-check-label`) like in `.form-label` elements.
> Added asterisk sign to checkbox element label with .required class

- src/scss/_dark.scss
This is my first PR in this project. I couldn't find any contribution guideline so feel free to any changes in this PR if needed.
Changes:
- added dark background to classes: `  .card-footer, .card-stacked::after, .card-tabs .nav-tabs .nav-link`.
> Fixed cards background in dark theme mode

- src/js/tabler.js
Tooltips placement wasn't working at all...
> Tooltip and popover placement fix

- src/scss/_dark.scss
I found a few more bugs in dark mode so I fixed for myself and I share effects my work. 
There are more things to improve but I can't fix everything at once. I develop private project which using tabler so you can expect more small fixes added occasionally.
> Some dark theme fixes

- src/js/tabler.js
- src/pages/_includes/ui/toast.html
> [dev-toasts-initialization] initialize toasts on app start

- src/js/tabler.js
- src/pages/_docs/form-helpers.md
- src/pages/_docs/tooltips.md
- src/pages/_includes/forms/form-elements-1.html
> [dev-form-helpers] fix data-content and data-html attributes

- src/pages/_docs/cursors.md
- src/scss/_utilities.scss
Add new utility classes for some of the other more common cursors:
- Default
- None
- Help
- Progress
- Wait
- Text
- Vertical Text
- Grab
- Grabbing
> Add more cursors

- src/pages/_docs/badges.md
- src/scss/_variables.scss
- src/scss/ui/_badges.scss
> fix #960 - Badges not honoring font sizes

- src/pages/_docs/avatars.md
- src/pages/_docs/badges.md
- src/pages/_includes/cards/company-lookup.html
- src/pages/_includes/cards/icons.html
- src/pages/_includes/cards/music/tracks-list.html
- src/pages/_includes/cards/order-statistics.html
- src/pages/_includes/cards/small-stats-2.html
- src/pages/_includes/ui/progress-description.html
- src/scss/_utilities.scss
- src/scss/ui/_badges.scss
> bug #973 `fw-...`, `.fs-...` is missed

- src/pages/_data/menu.yml
- src/pages/_includes/cards/body-placeholder.html
- src/pages/_includes/ui/card-dropdown.html
- src/pages/_includes/ui/map-vector.html
- src/pages/_includes/ui/svg.html
- src/pages/card-actions.html
- src/pages/cards-masonry.html
- src/pages/cards.html
- src/scss/ui/_buttons.scss
- src/scss/ui/_cards.scss
**Card actions:**
**Card masonry layout:**
> new card action demos

- src/js/demo.js
> Update demo.js for code improvements

- src/pages/_data/charts.yml
- src/pages/_includes/cards/card-image.html
- src/pages/_includes/cards/card-tabs.html
- src/pages/_includes/cards/card.html
- src/pages/cards.html
- src/pages/charts.html
- src/scss/mixins/_functions.scss
- src/scss/ui/_avatars.scss
- src/scss/ui/_cards.scss
- src/scss/ui/_grid.scss
- src/scss/ui/_nav.scss
> Cards fixes, new demos

- src/pages/_data/menu.yml
- src/pages/_includes/layout/footer.html
- src/pages/_includes/layout/navbar.html
- src/pages/_layouts/default.html
- src/pages/layout-boxed.html
- src/pages/layout-fluid-vertical.html
- src/pages/layout-fluid.html
- src/scss/layout/_core.scss
- src/scss/layout/_dark.scss
> Boxed layout

- src/scss/layout/_dark.scss
- src/scss/ui/_lists.scss
Simpler list group item color scheme and all states now work in dark mode.
Fixes #1035
> List group item colors in light and dark modes

- src/scss/layout/_dark.scss
- src/scss/ui/_toasts.scss
> Fix toasts in dark-mode being to bright

- gulpfile.js
- src/pages/_docs/carousel.md
- src/pages/_includes/example.html
- src/pages/_includes/ui/carousel.html
- src/pages/carousel.html
- src/scss/_core.scss
- src/scss/_variables.scss
- src/scss/ui/_carousel.scss
Demo: https://tabler-git-dev-carousel-tabler-ui.vercel.app/carousel.html
Docs: https://tabler-git-dev-carousel-tabler-ui.vercel.app/docs/carousel.html
> New carousel indicators: dots, vertical, thumbs

- src/scss/utils/_colors.scss
> Fix #1082: Make sure text-$color overwrites bg-$color

- src/pages/_data/menu.yml
- src/pages/pricing-table.html
- src/scss/_variables.scss
- src/scss/ui/_cards.scss
- src/scss/utils/_colors.scss
> new: Pricing table

- README.md
This is just a tiny update of the README. 
Probably only relevant for people trying to build tabler the first time locally, because everyone runs into the problems exactly one time and then never again 😁 
Feel free to close this unmerged, but I was stumbling upon those points and thought I'll share them.
> improve docs for first time contributors

- package-lock.json
- package.json
- src/pages/_data/docs.yml
- src/pages/_data/inline-players.yml
- src/pages/_data/libs.json
- src/pages/_data/menu.yml
- src/pages/_docs/inline-player.md
- src/pages/_includes/ui/inline-player.html
- src/pages/inline-player.html
- src/scss/tabler-vendors.scss
- src/scss/vendor/_plyr.scss
> Inline player

- src/pages/pricing-table.html
fixes https://github.com/tabler/tabler/issues/1167
Whitespace changes seem to have been automatically applied by my IDE based on the repositories .editorconfig. Not sure if this is desired but i can revert those if not.
> Fix the responsiveness of the pricing table page

- src/scss/layout/_navbar.scss
> Fixes Issue #1149. Vertical nav overflow.

- README.md
Visualise is the British spelling of visualize and inconsistent with the rest of the file (uses color instead of colour, etc), updated to match document
> Updating spelling

- src/pages/_docs/icons.md
- src/scss/ui/_icons.scss
Adds the icon animation classes from [tabler-icons.io](https://tabler-icons.io/) to tabler itself so everyone can use them.
fixes: https://github.com/tabler/tabler/issues/974
> Add icon pulse/tada/rotate animations

- gulpfile.js
- src/js/demo-theme.js
- src/js/demo.js
- src/pages/_layouts/base.html
Load the theme code as fast as possible to prevent flashing the light theme before fetching and applying the dark theme from the URL or localstorage.
fixes https://github.com/tabler/tabler/issues/1172
> Fix flashing white when dark theme is enabled

- src/scss/ui/_pagination.scss
fixes: https://github.com/tabler/tabler/issues/1202
> fix transparent hover background in pagination

- Gemfile
- Gemfile.lock
- gulpfile.js
- package-lock.json
- package.json
- src/pages/_data/pages.yml
- src/pages/_docs/progressbg.md
- src/pages/_includes/cards/most-visited-pages.html
- src/pages/_includes/cards/tables/progressbg.html
- src/pages/_includes/layout/analytics.html
- src/pages/_includes/ui/progress.html
- src/pages/_includes/ui/table.html
- src/pages/tables.html
- src/scss/_variables.scss
- src/scss/fonts/_webfonts.scss
- src/scss/layout/_core.scss
- src/scss/mixins/_functions.scss
- src/scss/ui/_avatars.scss
- src/scss/ui/_cards.scss
- src/scss/ui/_forms.scss
- src/scss/ui/_legend.scss
- src/scss/ui/_progress.scss
- src/scss/ui/_tables.scss
- src/scss/ui/_type.scss
- src/scss/utils/_colors.scss
> new `progressbg` component

- src/pages/_docs/cards.md
> fix typo in cards.md

- src/pages/_includes/ui/chart-heatmap.html
Changed the javascript chart initialization to conform with `chart.html` and `chart-sparkline.html`
> Fix ApexChart heatmap initialization on the charts docs page

- src/scss/ui/_toasts.scss
fixes: https://github.com/tabler/tabler/issues/1166
> Remove the odd left border on toasts

- src/pages/_docs/customize.md
fix https://github.com/tabler/tabler/issues/1169
> Fix code sample in the customize tabler docs

- src/pages/_includes/ui/tinymce.html
fixes https://github.com/tabler/tabler/issues/1215
> Toggle TinyMCE dark mode and skin based on the set tabler theme

- src/pages/_data/menu.yml
- src/pages/_includes/cards/sign-in.html
- src/pages/_includes/forms/sign-in.html
- src/pages/sign-in-cover.html
- src/pages/sign-in-illustration.html
> Sign in with cover

- src/js/src/dropdown.js
- src/scss/ui/_dropdowns.scss
> fixed dropdown issue on tables issue #1249

- package-lock.json
- src/scss/ui/_legend.scss
Fixed color of Free space section in Progress bar should be same as its labeled color.
> Resolved issue 1276

- src/pages/_data/docs.yml
- src/pages/_docs/tracking.md
- src/pages/_includes/parts/dropdown/months.html
- src/pages/_includes/ui/tracking.html
- src/scss/_core.scss
- src/scss/_variables.scss
- src/scss/ui/_cards.scss
- src/scss/ui/_tracking.scss
> new `tracking` component

- src/pages/_data/menu.yml
- src/pages/_includes/layout/navbar-menu.html
- src/pages/badges.html
- src/scss/_core.scss
- src/scss/layout/_animations.scss
- src/scss/mixins/_mixins.scss
- src/scss/ui/_avatars.scss
- src/scss/ui/_badges.scss
- src/scss/ui/_buttons.scss
- src/scss/ui/_icons.scss
- src/scss/ui/_loaders.scss
Demo: https://tabler-git-dev-badges-tabler-io.vercel.app/badges.html
> New `badges` page

- src/pages/_data/menu.yml
- src/pages/steps.html
- src/scss/_variables.scss
- src/scss/ui/_breadcrumbs.scss
- src/scss/ui/_steps.scss
> Steps improvements

- src/scss/_variables.scss
- src/scss/ui/forms/_form-colorinput.scss
> fix #1328: color input should show different color for inner check symbol on white ellipse

- src/scss/_variables.scss
- src/scss/ui/_forms.scss
> fix #1180: number input with `form-control-sm` looks weird

- src/pages/job-listing.html
> fix #1348: Make job listing responsive for smaller devices

- src/pages/_docs/avatars.md
- src/pages/_includes/ui/avatar.html
- src/scss/_variables.scss
- src/scss/ui/_avatars.scss
avatars list is now stacked: 
fixes: #1370
> fix #1370: avatar stacked list is not stacked anymore

- src/pages/_docs/form-elements.md
- src/pages/_includes/forms/form-elements-2.html
- src/pages/_includes/ui/form/input-group.html
- src/scss/_variables.scss
- src/scss/ui/_status.scss
- src/scss/ui/_type.scss
> add input with appended `<kbd>`

- README.md
Found some grammatical errors in the readme file. Fixing them improves the overall experience of the developers planning to use the library.
> correct grammatical errors in README.MD

- src/pages/_data/menu.yml
- src/pages/trial-ended.html
> Trial ended page

- src/scss/_utilities.scss
Fixes https://github.com/tabler/tabler/issues/1525
> Fix bug where border-1, border-2, etc don't work

- .changeset/rare-pumpkins-pull.md
- src/js/demo-theme.js
- src/pages/_includes/layout/navbar-logo.html
- src/pages/_includes/layout/navbar-search.html
- src/pages/_includes/layout/navbar-side.html
- src/pages/_includes/layout/navbar.html
- src/pages/_includes/layout/sidebar.html
- src/pages/_includes/ui/dropdown-menu.html
- src/pages/_includes/ui/form/input-icon.html
- src/scss/_config.scss
- src/scss/_variables-dark.scss
- src/scss/_variables.scss
- src/scss/demo.scss
- src/scss/demo/_examples.scss
- src/scss/layout/_dark.scss
- src/scss/layout/_navbar.scss
- src/scss/layout/_root.scss
- src/scss/mixins/_mixins.scss
- src/scss/ui/_tables.scss
- src/scss/vendor/_apexcharts.scss
- src/scss/vendor/_tinymce.scss
This PR unifies the dark mode in our project with the latest Bootstrap API and improves the design and functionality of dark mode elements. The updated dark mode provides a more consistent and polished user experience across our application.
> Unify dark mode with latest Bootstrap API and improve dark mode elements

- .changeset/odd-terms-tap.md
- src/scss/_variables.scss
- src/scss/ui/_grid.scss
- src/scss/ui/_tables.scss
> Fix form controls bugs in dark mode

- .changeset/curvy-fishes-lie.md
- .github/workflows/bundlewatch.yml
- package.json
- pnpm-lock.yaml
- src/pages/_data/libs.json
- src/pages/_data/menu.yml
- src/pages/_includes/ui/rating.html
- src/pages/stars-rating.html
- src/scss/tabler-vendors.scss
- src/scss/vendor/_stars-rating.scss
This PR adds a new Star Ratings component to our project, using the `star-rating.js` JavaScript library. The new component provides users with a fully customizable star rating system, allowing them to rate items with stars that can be customized in size, color, and image.
To add the new component, I integrated the `star-rating.js` library into our project and created a new HTML and CSS file to display the star ratings. The stars are fully customizable, with options to change the size, color, and image of the stars to match the look and feel of our application.
The new Star Ratings component provides users with a simple and intuitive way to rate items using stars. Users can click on a star to select a rating, with the selected star and all stars to the left of it being filled in. The …
> Add customizable Star Ratings component using `star-rating.js` library

- .changeset/beige-hats-prove.md
- docs/components/buttons.mdx
Updated Icons can be found link
> Updated link to icons documentation

- .changeset/fluffy-insects-lay.md
- .prettierrc
- src/pages/2-step-verification-code.html
- src/pages/2-step-verification.html
- src/pages/_data/countries.yml
- src/pages/_data/menu.yml
- src/pages/_includes/parts/form/input-datalist.html
- src/pages/_layouts/single.html
- src/scss/_variables.scss
- src/scss/vendor/_coloris.scss
- src/scss/vendor/_tom-select.scss
> Adding Two-Step Verification Pages

- .changeset/sharp-colts-grab.md
- src/pages/_includes/layout/navbar-side.html
- src/pages/_includes/layout/navbar.html
- src/scss/_variables.scss
- src/scss/layout/_dark.scss
- src/scss/layout/_root.scss
> Resolved light dropdown issue on dark theme

- .changeset/soft-mangos-tie.md
- src/scss/_variables.scss
- src/scss/ui/_avatars.scss
Fixes #1567
Untested, I can't build Tabler core... will update the PR if it works.
> allow to configure avatar-list-spacing 

- src/pages/_includes/layout/navbar-menu.html
- src/scss/_variables-dark.scss
- src/scss/_variables.scss
- src/scss/layout/_navbar.scss
- src/scss/layout/_page.scss
- src/scss/layout/_root.scss
- src/scss/ui/_timeline.scss
> Revert "Navbar unify"

- demo/job-listing.html
- src/pages/job-listing.html
**Issue Link:** https://github.com/tabler/tabler/issues/1638
**Light mode:**
**Dark mode:**
> update badge-pill border color on job listing 

- .changeset/shiny-dolls-shop.md
- src/pages/_data/chat.yml
- src/pages/_includes/ui/chat.html
- src/scss/_core.scss
- src/scss/ui/_cards.scss
- src/scss/ui/_chat.scss
> New Chat component

- .changeset/healthy-bikes-cry.md
- Dockerfile
Update Dockerfile to remove/add proper ADD commands and include the correct packages to be able to build/run
> Fix Dockerfile

- src/scss/vendor/_litepicker.scss
Hi, my pull request solves the issue. Thanks.
> Updated the spelling of prev to previous in the file

- src/scss/_variables-dark.scss
- src/scss/_variables.scss
- src/scss/layout/_dark.scss
- src/scss/layout/_root.scss
- src/scss/ui/_buttons.scss
This PR attempts to repair some of the broken variable names from the Bootstrap 5 transition somewhere between betas 16 and 19 (and now beta 20 as of this morning) and to improve the accessibility with a more visually consistent color-step palette.
(Apologies for my non-hi-DPI screen with which I took these screenshots...)
Border color on hover was black because of missing variable:
I restored the previous look by repairing the variable, which makes it a dark gray (which IMO looks better too -- this is the way it was in beta ~16):
Card caps bg is currently too hard to see:
Now it is visible again, closer to beta 16:
(Thus this PR fixes #1592)
It resolves a few accessibility issues as well:
- Hover BGs are now visible, they got lost somewhere between beta 16 and 19. Now they're even more …
> Fix some missing variables, minor tweaks to some colors

- src/scss/ui/_type.scss
> Fix disabled css class for links

- src/pages/lightbox.html
> Fix #1757: Fix lightbox spacing on tablet and mobile in demo

- src/scss/ui/_alerts.scss
fix alert bg prefix and surface variable
> fix alert bg prefix

- .changeset/long-eggs-work.md
- _config.yml
- src/scss/layout/_page.scss
> map pages fixes

- src/pages/_includes/ui/table.html
- src/pages/tables.html
- src/scss/ui/_tables.scss
> Revert "Fix missing tfoot styling"

- .changeset/ninety-dancers-doubt.md
- SECURITY.md
I just added some punctuation so it is way easier to read, It also can help while you guys are making more changes.
> Adding punctuation to "SECURITY.md"

- src/scss/utils/_colors.scss
Fix https://github.com/tabler/tabler/issues/1909
> FIX 1909 - Wrong gray colors

- .changeset/fluffy-papayas-greet.md
- src/pages/_layouts/error.html
- src/pages/_layouts/single.html
> Replace .page-center with .my-auto in single page layouts

- .changeset/witty-pens-trade.md
- src/scss/vendor/_litepicker.scss
Before changes:  
After changes:
> Fix colors in date range datepicker

- .changeset/chilly-vans-leave.md
- docs/components/divider.mdx
- src/scss/ui/typo/_hr.scss
> Make horizontal rule direction aware

- .changeset/orange-maps-fetch.md
- src/scss/ui/_tables.scss
Is also set by included subheader class.
Fixes #1897
> Remove duplicated setting of color in th

- .changeset/hungry-poets-speak.md
- src/pages/stars-rating.html
> Fix ids of custom size star ratings

- .changeset/eight-ladybugs-invite.md
- src/scss/_variables.scss
Fixes overlapping the dropdowns by other elements.
> Remove invalid z-index setting for dropdown

- .changeset/selfish-avocados-battle.md
- src/scss/_variables.scss
> Mark value of $font-family-monospace !default

- .changeset/kind-days-sneeze.md
- src/scss/ui/_buttons.scss
> Set font-size of webfont icon inside a button

- .changeset/soft-suits-count.md
- src/scss/ui/_forms.scss
> Do not display empty <fieldset>

- .changeset/good-birds-smash.md
- src/scss/layout/_navbar.scss
> Fix color of disabled dropdown-item

- .changeset/little-badgers-care.md
- src/scss/vendor/_tom-select.scss
Fixes #2079 
Before fix:  
After fix:
> Fix colors of disabled tom-select

- .changeset/nice-jeans-tie.md
- package.json
- src/scss/vendor/_apexcharts.scss
> Fix size of apexcharts tooltip marker

- README.md
As bundler has been removed in 782f0f5.
> Remove mention of bundler from README

- .changeset/silly-lobsters-move.md
- docs/ui/components/buttons.mdx
* Fixed background-image in buttons with avatars.
* Removed duplicated code blocks.
* Fixed links to some icons.
* Twitter icon button replaced with X.
> Improve documentation for buttons

- .changeset/odd-boats-hear.md
- docs/ui/components/charts.mdx
> Fix apexcharts heatmap example in docs

- .changeset/itchy-ligers-repair.md
- .github/workflows/bundlewatch.yml
- core/package.json
- core/scss/_config.scss
- core/scss/_utilities.scss
- core/scss/_variables.scss
- core/scss/mixins/_functions.scss
- core/scss/ui/_type.scss
- preview/pages/text-features.html
- turbo.json
> New text features page

- .changeset/warm-planets-look.md
- docs/icons/libraries/webfont.mdx
- docs/icons/static-files/png.mdx
- docs/icons/static-files/svg.mdx
> Fix instruction for CDN icons version

- .changeset/thick-kids-glow.md
- core/scss/_variables.scss
- core/scss/layout/_navbar.scss
- core/scss/marketing/_browser.scss
- core/scss/marketing/_hero.scss
- core/scss/marketing/_sections.scss
- core/scss/ui/_nav.scss
- preview/pages/_includes/layout/navbar-side.html
> Enhance navbar styles with new hover effects and color variables

- .changeset/tall-apples-remember.md
- README.md
- docs/ui/getting-started/index.mdx
Small change to improve the look of the readme
> Fixed missing images in the README and getting started page + minor formatting changes

- .changeset/ninety-cars-hug.md
- preview/pages/2-step-verification-code.html
> Decrease padding of form-control input in 2-step-verification-code

- .changeset/twenty-radios-punch.md
- README.md
This commit begins updating README.md to remove duplications, outdated information, and improve the flow of the setup/build instructions.
TODO: Possibly remove or rewrite several other parts of the file based on further comments. Remaining questions:
- [README.md#-features](https://github.com/tabler/tabler/blob/dev/README.md#-features) - refers to [Tabler React](https://github.com/tabler/tabler-react) which is now an archived repo. Is it desirable to keep linking to it? (My guess is possibly not?)
- There are two 'Contributors' sections. One refers to the [All contributors specification](https://github.com/all-contributors/all-contributors). (Is is still desired to use that? If not, I'm assuming we could remove it)
- "Building locally" instructions are not fully tested yet - I can do so …
> Improve README.md

- core/scss/_utilities.scss
- core/scss/utils/_colors.scss
- preview/pages/colors.html
Preview: https://tabler-git-dev-gradients-tabler-io.vercel.app/colors.html
> Add gradient background utilities

- .changeset/large-elephants-camp.md
- preview/pages/_includes/layout/navbar-logo.html
> Replace HTML `alt` attribute to `aria-title` used on SVG element

- .changeset/chatty-bottles-jam.md
- core/scss/ui/_accordion.scss
- preview/pages/_includes/ui/accordion.html
> Rollback accordion component structure

- .changeset/ten-walls-smell.md
- core/scss/tabler-vendors.scss
- core/scss/vendor/_turbo.scss
- pnpm-lock.yaml
- preview/package.json
- preview/pages/_data/libs.json
- preview/pages/_includes/layout/js-libs.html
- preview/pages/_includes/layout/js.html
- preview/pages/_layouts/base.html
- preview/pages/turbo-loader.html
> Add Turbo library integration and update dependencies

- .changeset/hip-years-develop.md
- core/scss/vendor/_jsvectormap.scss
- core/scss/vendor/_nouislider.scss
- core/scss/vendor/_tom-select.scss
- preview/pages/_data/libs.json
> Fix tooltip colors in vector maps

- .changeset/lemon-penguins-sin.md
- preview/pages/_includes/layout/navbar-menu.html
> Fix color badge in navbar menu

- .changeset/proud-cheetahs-provide.md
- core/scss/_variables.scss
- core/scss/ui/_avatars.scss
- preview/pages/_data/menu.json
- preview/pages/_data/people.json
- preview/pages/_includes/ui/avatar-upload.html
- preview/pages/_includes/ui/avatar.html
- preview/pages/_includes/ui/icon.html
- preview/pages/avatars.html
> Add avatars page with various demos of avatars

- .changeset/wicked-cougars-repeat.md
- core/scss/mixins/_mixins.scss
> Make scrollbar track transparent

- core/scss/ui/_type.scss
remove incorrect horizontal steps orientation
fixes #2301 
fixes #2267
> fix #2267 (steps layout issue)

- .changeset/new-rats-argue.md
- docs/content/ui/components/ribbons.md
fixes #2296 
* Text ribbon with a text instead of icon.
* Removed duplicated code examples.
* Fixed link to base colors.
* Improved description of bookmark ribbon.
> Fix ribbon component in the documentation

- .changeset/rude-jobs-rush.md
- shared/includes/layout/css.html
> 2304-bug-preview-site-rtl-mode-demo-broken

- .changeset/gentle-students-visit.md
- docs/content/ui/components/switch-icon.md
> Fix switch icon examples in documentation

- .changeset/twelve-rings-sleep.md
- docs/content/ui/getting-started/how-to-contribute.md
- docs/content/ui/getting-started/installation.md
> Add missing `.steps-vertical` classes in docs

- .changeset/silly-pears-mix.md
- docs/content/ui/components/inline-player.md
> Fix: Replace non-existent Vimeo file and enhance the inline player documentation

- .changeset/good-experts-lick.md
- shared/e11ty/filters.mjs
- shared/layouts/docs/default.html
Added dynamic metadata generation for titles, descriptions, and Open Graph/Twitter tags in docs layout. Introduced an `absolute_url` filter in Eleventy for consistent URL handling across the site. These changes improve SEO and ensure proper canonical link generation.
Closes #2290
> Fix: Add missing metadata for Tabler Documentation

- .changeset/rude-shrimps-smile.md
- core/scss/layout/_core.scss
> Remove unnecessary `!important` from body padding

- .changeset/heavy-fireants-vanish.md
- shared/includes/cards/invoices.html
> Improve card footer layout and enhance entry display format in invoices

- .changeset/blue-spoons-sleep.md
- core/scss/layout/_navbar.scss
- core/scss/ui/_buttons.scss
- core/scss/ui/_cards.scss
- core/scss/ui/_switch-icon.scss
- docs/content/ui/components/badges.md
- docs/content/ui/components/switch-icon.md
- package.json
- pnpm-lock.yaml
- preview/pages/cards.html
- preview/pages/emails.html
- preview/pages/form-layout.html
- preview/pages/layout-vertical-right.html
- shared/includes/cards/card.html
- shared/includes/cards/profile-timeline.html
- shared/includes/cards/small-stats-2.html
- shared/includes/cards/small-stats.html
- shared/includes/cards/table-users.html
- shared/includes/layout/js.html
- shared/includes/layout/sidebar.html
- shared/includes/marketing/sections/cta.html
- shared/includes/parts/demo-layout.html
- shared/includes/ui/button.html
- shared/layouts/default.html
- shared/layouts/docs/default.html
Replace all classes ended by `*-left`, `*-right` to `*-start`, `*-end` with fallback
> Update class names from left, right to start, end

- .changeset/button-ghost.md
- .changeset/icon-stroke-width.md
- .changeset/onboarding-page.md
- .changeset/progress-background.md
- .changeset/progress-sizes.md
- .changeset/progress-steps.md
- .changeset/progress-transitions.md
- .changeset/skip-link-accessibility.md
- .changeset/trending-icons.md
- .cursor/rules/changelog.mdc
- core/scss/_variables.scss
- core/scss/ui/_buttons.scss
- core/scss/ui/_icons.scss
- core/scss/ui/_progress.scss
- core/scss/ui/forms/_form-selectgroup.scss
- docs/content/ui/components/progress.md
- preview/pages/onboarding.html
- preview/pages/progress.html
- shared/data/menu.json
- shared/includes/cards/tables/progressbg.html
- shared/includes/docs/navbar.html
- shared/includes/layout/skip-link.html
- shared/includes/settings.html
- shared/includes/ui/progress-steps.html
- shared/includes/ui/progress.html
- shared/includes/ui/progressbg.html
- shared/includes/ui/trending.html
This pull request introduces significant enhancements to the progress bar components, adds new onboarding and progress demo pages, and improves UI consistency and maintainability. The most notable changes include the addition of step-based progress bars, new progress bar sizes and features, a reusable progress background component, and updates to documentation and demo pages.
**Progress Bar Enhancements:**
- Added new step-based progress bar (`progress-steps`) with customizable count, labels, and active step, including a new include file `progress-steps.html` and supporting SCSS styles. 
- Introduced new progress bar sizes (`progress-lg`, `progress-xl`) and improved transitions for progress bars.
- Enabled striped and animated progress bars with new options in the `progress.html` include. …
> Add progress page
