tabler/tabler

- src/assets/scss/dashboard/_aside.scss
- src/assets/scss/dashboard/_cards.scss
- src/assets/scss/dashboard/_grid.scss
- src/assets/scss/dashboard/_layout.scss
- src/assets/scss/dashboard/bootstrap/_media.scss
IE11 has issues with vertically flexed items when the `flex` property is defined in the short form e.g. "flex: 1". This update expands the definition to their full form which resolved major layout issues in IE11. (sort of fixes #18)
Before
After
> Fix flex issues in IE11

- src/_data/menu.yml
Hi!
I fix broken link to blog section in the menu items 😉
> Replace duplicate blog's menu items with carousel

- src/_includes/cards/form-all-elements.html
People are mistaking the "Icons input" demo as "gender input" due to the icons used. This changes the icons from male and female to day and night (#37)
> Change input icon demo to sun and moon

- src/_includes/cards/form-all-elements.html
- src/assets/scss/dashboard/forms/_custom-selectgroup.scss
This PR adds a vertical layout for the `selectgroup` form element. It is enabled by adding a `selectgroup-vertical` on the container.
```html
<div class="selectgroup selectgroup-vertical">
</div>
```
> Add vertical layout for selectgroup

- dist/forgot-password.html
- dist/login.html
- dist/register.html
- src/_layouts/single.html
Noticed a broken Tabler logo on **Login**, **Register** and **Forgot Password** pages while I was browsing the theme.
The fix seems to be trivial, so I decided to address that since it didn't look right to show the demo with broken images.
Hope this would help to make things even better! 😃 
Please find below a comparison `before` vs. `after` for each page adjusted.
`before`
`after`
`before`
`after`
`before`
`after`
> Fix issue with broken 'tabler.svg' logo on 'Login', 'Register' and 'Forgot Password' pages

- src/assets/scss/bundle.scss
placeholder `~` in path not not supported in SASS. See https://sass-lang.com/documentation/file.SASS_REFERENCE.html#import
> Fix bootstrap path in bundle.scss

- src/assets/scss/dashboard/_type.scss
The `text-decoration-skip` spec has changed
> text-decoration-skip fix

- package.json
`yarn dist` and `yarn jekyll-serve` don't run on mac without this change.
> Add "bundle exec" to use bundled, not latest versions of the deps

- src/assets/scss/dashboard/_selectize.scss
The `#` needed to be URL encoded
> Fix dropdown icon in latest Chrome

- README.md
Adds ember-tabler to the Single Page Applications list (in alphabetical order, not trying to offend anyone).
ember-tabler comes with:
- a fully working application skeleton (simply copy and start running tabler)
- Ember components for mobile menu etc.
- production ready so with deeplinks, catchall routes, etc
- tests
[Hardened demo found here](https://alt3.github.io/ember-tabler/)
> Add ember-tabler to the readme SPA list

- pages/_includes/cards/invoices.html
When a user clicks on the `action` button in the invoice table, dropdown makes some extra spaces below the table which causes jumping.
Adding `overflow-hidden` to the `table` element.
> Fix invoice table jumping

- README.md
Install Ruby link in README was not working, adding "www" fixes the issue.
> fix install Ruby link to close #568

- scss/ui/_avatars.scss
This updates the status badge of avatar icons so that the badge will match the avatar size.
Before:
After:
I believe the easiest option is to just set the width/height of the status badge to 1/4th the avatar w/h. From the options I tried, it looks the best while requiring hardly any changes.
> Avatar status badges should match the avatar size

- scss/ui/_alerts.scss
There is an issue with line alignment when you define a modal, with an alert & anchor, example: https://jsfiddle.net/57h8qdya/
Before
After
> Remove vertical-align for alert anchor elements

- package.json
We are currently trying to refactor our UI using tabler.
On my machine, since I added the `@tabler/core` package, `npm install` takes up to 12 minutes (was about 30 seconds before this change). I wanted to try `pnpm`, but it does not handle short commit hash in dependencies specs, and fails with this message: ` ERROR  Could not resolve c63aebc to a commit of git://github.com/twbs/bootstrap.git.`.
Using the full hash could permit usage of `pnpm` to fetch your wonderful creation.
> Permit installation using pnpm

- src/pages/_includes/cards/card-tabs.html
- src/pages/cards.html
- src/scss/ui/_cards.scss
Changes:
- ```.border-0``` is applied to all child cards and tabs. To build a page with lots of borderless cards this class can be set on the parent element instead of on each individual card.
- Prevents ```.card-active``` from breaking like [this](https://i.imgur.com/TkLge82.png).
- Reduces the opacity of ```.card-stacked``` when ```.border-0``` is active to keep the stacked look.
- Adds new examples in the cards page.
> Improve cards with no border

- src/scss/ui/forms/_validation.scss
Lite validation was only work for form fields with the `.form-control` class. Selects
use the `.form-select` class. This change also applies lite validation for the selects.
> Make lite validation also work properly for form select

- src/scss/utils/_colors.scss
Fix for https://github.com/tabler/tabler/issues/984 - [BUG] Extra background colors not working on table/td elements
> Update _colors.scss - Fix for #984

- src/scss/ui/_badges.scss
Closes #1006 
Improves vertical alignment of empty `.badge` elements.
> Fix vertical alignment of empty badge elements

- src/scss/fonts/_webfonts.scss
I added the `font-display: swap;` tag when loading the Inter font to improve the experience on slower connections.
It will make the text appear immediately with a fallback font and swap it with the Inter font as soon as the font is loaded. This shouldn't have any visual change for most users with a proper internet connection, but for slower connections - especially on mobile - this can make a huge difference.
More infos: https://developers.google.com/web/updates/2016/02/font-display#swap
> add font-display: swap; to improve font loading

- src/scss/ui/_forms.scss
How to test:
- Open firefox
- Go to forms
- Click fields above the selects
- Use tab to move into the next field
- It should not go blank
> Fix #1079: Fix select being blank when using tab to highlight field

- src/pages/_data/selects.yml
- src/pages/_includes/cards/form/layout.html
- src/pages/_includes/forms/form-elements-6.html
- src/pages/_includes/ui/select.html
@rjd22 here is a PR that adds optgroup examples in the form page, so they can be tested easily
See also #1024 and #1098
This is default browser (Safari) rendering:
And this is how Tom-Select currently looks:
This is how it looks normally with TomSelect and Bootstrap 5:  https://tom-select.js.org/examples/optgroups/
**UPDATE**
I found the issue that is causing it.
You are importing the [tom select bootstrap 5](https://github.com/tabler/tabler/blob/main/src/scss/vendor/_tom-select.scss#L1) css file, but you are preventing the rules from being applied. They are prefixed like this: `.#{$select-ns}-dropdown` where `select-ns` variable is `ts` by default, resulting in rules like these:
```css
.ts-dropdown {
.optgroup-header {
font-size: $font-size-sm;
line-height: $line-height-base;
}
}
```
But …
> added optgroup form examples

- .github/workflows/codeql-analysis.yml
- .github/workflows/test.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- src/pages/_data/docs.yml
- src/pages/_docs/popover.md
This adds an example page to showcase Popovers:
https://getbootstrap.com/docs/5.0/components/popovers/
Currently there is a bug in dark mode, probably due to #1145, which I initially wanted to work on:
But my frontend voodoo is not good enough.
The component is already using variables, but those seem to be defined for light only:
Anyway, I wanted to add the docs page in this PR only:
The content was improved and one example added after taking the screenshot, please check the Vercel deployment:
https://tabler-git-fork-kevinpapst-popover-tabler-ui.vercel.app/docs/popover.html
> added popover docs page

- package-lock.json
- package.json
- src/pages/datatables.html
A number of fixes for the datatables preview page (see https://preview.tabler.io/datatables.html)
- Add list.js to the devDependencies to actually make sorting columns work
- Wrap the table in `table-responsive` to show properly on tablet and mobile
- make the progress text be full with on tablet/mobile to prevent breaking out of the table.   
- (other package.json changes are just alphabetising)
> Make the datatables preview page functional

- src/pages/_includes/layout/homepage.html
Small fix that bothered me on the homepage.
Viewing the [preview homepage](https://preview.tabler.io/) on a tablet showed this big empty space.
You can reproduce it by opening element inspector in your browser and setting the dimensions to iPad air for example.
> Make development activity chart full width on tablets

- src/scss/ui/_lists.scss
List groups look a little of because they are by default darker than the rest of the content. This PR switches the default color with the active color.
Old:
https://preview.tabler.io/lists.html?theme=light
https://preview.tabler.io/lists.html?theme=dark
New:
https://tabler-git-switch-list-group-colors-tabler-ui.vercel.app/lists.html?theme=light
https://tabler-git-switch-list-group-colors-tabler-ui.vercel.app/lists.html?theme=dark
> Switch active and default colors of list groups

- src/pages/_docs/modals.md
fix for modal bugs reported in https://github.com/tabler/tabler/issues/1145
Bootstrap 5.2 moved to using CSS variables for modals (https://github.com/twbs/bootstrap/pull/36060) which are set on the `modal` class. As this class is not included in the sample code, the other modal classes (like `modal-dialog` and `modal-content`) could not find the correct variables to set things like the padding/margin etc.
This PR will add the `modal` class to the sample code as it is required for both the end user and correctly rendering the modals in the documentation.
> Fix rendering of modal examples on docs page

- src/pages/_includes/cards/form/layout.html
- src/scss/ui/_forms.scss
According to the Bootstrap docs labels do get `col-form-label` in horizontal forms and not `form-label` as in classical form layout. See examples at https://getbootstrap.com/docs/5.2/forms/layout/#horizontal-form . Some frameworks that render forms (e.g. PHP Symfony) do stick to the original definition and I was missing the * in some forms.
Tabler until now does only style `form-label`, there is no mention of `col-form-label`.
This was okay in most cases, but the `required` class isn't applied (compare before and after screenshots).
I adjusted the demo, so there is a showcase of the `required` class as well in horizontal forms. I also adjusted the used label class, so the demo HTML matches the HTML from the Bootstrap docs. 
Before:
After:
The screenshots were taken after adjusting the …
> Required form label for horizontal forms

- README.md
- demo/docs/download.html
- demo/docs/flags.html
- demo/docs/payments.html
- src/pages/_docs/download.md
- src/pages/_includes/docs/plugin.html
Continuing on from https://github.com/tabler/tabler-icons/pull/265.
I also noticed that the latest tag on NPM is actually linked to beta9 instead of 10 as seen here: https://www.npmjs.com/package/@tabler/core?activeTab=versions
That has a side-effect of the CDNs linking to beta9 instead of 10 when you use the `@latest` tag on it. Is that intentional?
> docs: switch unpkg to jsdelivr

- src/pages/_docs/tables.md
- src/scss/_variables.scss
- src/scss/ui/_tables.scss
I am not exactly an expert on scss, variables or mixins so i am not sure if this is the desired approach but the PR will shift the colors for variant tables to shade instead of tint when in dark mode.
fixes: https://github.com/tabler/tabler/issues/1193
> Use dark table variant colors in dark mode

- demo/form-elements.html
- src/pages/_includes/parts/form/input-radios-inline.html
- src/pages/_includes/parts/form/input-radios.html
- src/pages/_includes/ui/form/check.html
Sets a common name for the first two radio buttons in the "Radios" section. We keep the checked disabled radio input to demonstrate the display.
Sets a common name for the three inline radio buttons in the "Inline Radios" section.
Fix #1196
> Fix form elements demo page radio buttons

- .dockerignore
- Dockerfile
- README.md
This is simply a re-work of [PR-1192](https://github.com/tabler/tabler/pull/1192).
Alpine base image was requested, and I added it. Branch works locally with MacOS, Docker Desktop with the image holding 1.12GB of space.
> Added Dockerfile with alpine base

- gulpfile.js
- package-lock.json
- package.json
- src/scss/utils/_colors.scss
In #1213 the Sass implementation was switched from dart-sass to node-sass for some reason. Because node-sass is deprecated we should switch back to dart-sass. Also, it should only be listed in the devDependencies.
> Switch to dart-sass

- src/pages/_includes/cards/invoices.html
This fixes the issue mentioned here https://github.com/tabler/tabler/issues/1292
> fix: remove css that overrides dark theme color

- src/pages/_docs/form-image-check.md
- src/pages/_includes/forms/form-elements-3.html
- src/pages/_includes/parts/form/input-image-radio.html
- src/scss/ui/forms/_form-imagecheck.scss
> radio button version of image check

- src/pages/_includes/cards/card-tabs.html
- src/pages/_includes/cards/tabs.html
- src/pages/tabs.html
- src/scss/_variables.scss
- src/scss/layout/_dark.scss
- src/scss/layout/_navbar.scss
- src/scss/layout/_root.scss
- src/scss/ui/_buttons.scss
- src/scss/ui/_cards.scss
- src/scss/ui/_nav.scss
> Dark mode fixes

- .github/workflows/lockfiles.yaml
There were quite a lot of PRs in the past, which shipped changed **lock files**.
Those were mostly introduced by unexperienced contributors, but considering the popularity of Tabler and the amount of potential targets, this could be a real security risk:
https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/
There is a simple way to prevent that, which I am using in all my projects: a workflow that checks the PR for changed lock files and fails directly if a changed lockfile was included. The only persons allowed to push changes for those files are @codecalm and @dependabot (see e.g. #1296).
The used workflow is: https://github.com/xalvarez/prevent-file-change-action
What do you think @codecalm about the idea in general?
~~This PR is a draft …
> Security measure: fail PR if a lock file was changed

- demo/docs/flags.html
This PR replaces the PL flag in the Flags documentation with the rather neutral antarctica flag, as the white part of the PL flag is hard to see on the white background, which doesn't look too good in this example.
Before:
After:
> Replace hard to see flag in documentation

- src/pages/_data/menu.yml
Fixes a spelling mistake causing a 404 error.
> corrects spelling from "eneded" to "ended"

- src/scss/vendor/_tom-select.scss
This is a fix for the issue reported in #1392.
With this fix, select inputs may now be `fit-content`.
> Fix non full width selects #1392

- .changeset/shy-rockets-deliver.md
- package.json
- pnpm-lock.yaml
- src/pages/_data/icons.yml
This PR updates the icons used in the project to version 2.19, which includes 18 new icons.
> Update Tabler Icons to version 2.19 with 18 new icons added

- .changeset/heavy-chicken-cover.md
- package.json
- pnpm-lock.yaml
- src/pages/_data/icons.yml
This PR updates the icons used in the project to version 2.20, which includes 37 new icons.
> Update Tabler Icons to version 2.20 with 37 new icons added

- .changeset/hip-jobs-double.md
- docs/components/alerts.mdx
- src/pages/_data/menu.yml
- src/pages/_includes/ui/alert.html
- src/pages/alerts.html
- src/scss/ui/_alerts.scss
@codecalm I'm not sure I did this right. So much has changed in the last versions. What is the correct way to adapt the docs?
I also wanted to fix the issue with the docs hiding part of the alerts but was unable to understand what is used to generate them:
> fix: #1588 add important alert with title

- .changeset/stupid-dingos-train.md
- src/scss/_variables.scss
- src/scss/mixins/_mixins.scss
As of now, focus border and shadow color depend on scss variables, therefore tabler compilation.
IMO it shouldn't, actually nothing should depended on scss variables, specially colors.
This PR allows inputs border and shadow to depend on primary color css variable, devs will be able to do this;
> Avoid scss color dependency on :focus

- README.md
Removed extra `to` word in the line `We work hard to to provide continuous support for them.` in README.md.
> docs: Remove duplicate 'to' in documentation

- _config.yml
- docs/components/alerts.mdx
- docs/components/badges.mdx
- docs/components/buttons.mdx
- docs/components/cards.mdx
- docs/components/datagrid.mdx
- docs/components/divider.mdx
- docs/components/dropdowns.mdx
- docs/components/empty.mdx
- docs/components/inline-player.mdx
- docs/components/placeholder.mdx
- docs/components/range-slider.mdx
- docs/components/statuses.mdx
- docs/components/tables.mdx
- docs/components/timelines.mdx
- docs/components/toasts.mdx
- docs/components/tooltips.mdx
- site/styles/_docs.scss
- src/scss/vendor/_litepicker.scss
Some examples of fixes:
1. Tables  
->  
2. Tooltips  
-> 
3. Buttons  
-> 
4. Empty
->
5. Timelines
->
> Fix heights, scrolls and layouts of some examples in Docs

- site/components/Example.tsx
Replaces before using example variable.
Replace all hrefs, not only in <a> tags.
Should prevent opening whole site inside iframe in examples in Documentation.
> Fix replacing href="#" with href="javascript:void(0)"

- src/scss/ui/_dropdowns.scss
Fixes transparent scrollbar background in dropdown-menu, by setting `background-clip` to `border-box` for `dropdown-menu` class.
> Fix background of scrollbar in dropdown menu

- README.md
- site/README.md
Adds documentation in `tabler/site/README.md` pointing users to how to run documentation site locally. Reflects change in main README. 
For developers to be able to change the documentation site or run it locally, this clarifies the process. Furthermore, the `README.md` in the `site` directory was previously empty, this fills it in.
Documentation only change for clarity in local runs of doc site, no testing or production changes
> README Update for `site` documentation

- CHANGELOG.md
This PR fixes typos in **CHANGELOG.md** file.
Following typos have been fixed:
`atributes` -> `attributes`
No other changes.
> fix: typo in CHANGELOG.md

- src/scss/_variables.scss
> Fix #1754: Revert dropdown spacing to .5 rem

- src/pages/_includes/ui/table.html
- src/pages/tables.html
- src/scss/ui/_tables.scss
`tfoot` doesn't have the same behaviour as `thead`, leading to this behaviour;
This PR aims to fix it 👌
> Fix missing tfoot styling

- .changeset/mighty-mirrors-drum.md
- src/scss/layout/_navbar.scss
This PR aims to resolve the issue mentioned in #1473 
Steps taken to resolve:
1. Identified reason for discrepancy between horizontal and verticaldrop down menu items in the navbar - issue identified to be correlated to lack of distinction of colours for disabled items in vertical dropdown menu. 
2. Manually recreated issue by disabling all level 2 dropdown menu items in /src/…/navbar-menu.html (i.e. all components under Interface, Extra, Layout and Help are disabled).
NOTE: Issue (mentioned in #1473) persists as there is no clear visual distinction between disabled and enabled dropdown menu items; all are displayed in the same colour, even though the Layout’s dropdown items are disabled.
3. Identified the .scss file corresponding to navbar-menu.html in /src/…/_navbar.scss and …
> Update _navbar.scss with disabled dropdown menu items colour

- package.json
TinyMCE 7.0 have only some small BC breaks and it should be possible to use the new v7.0.0 version without having any issues.
This would prevent the following error when trying to upgrade to `tinymce@^7.0.0`:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @tabler/core@1.0.0-beta20
npm ERR! Found: tinymce@7.0.0
npm ERR! node_modules/tinymce
npm ERR!   tinymce@"^7.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional tinymce@"^6.4.2" from @tabler/core@1.0.0-beta20
npm ERR! node_modules/@tabler/core
npm ERR!   @tabler/core@"^1.0.0-beta20" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: tinymce@6.8.3
npm ERR! node_modules/tinymce
npm ERR!   peerOptional tinymce@"^6.4.2" from …
```
> Allow usage of version 7.x of the `tinymce` peer dependency

- .changeset/lucky-impalas-smash.md
- README.md
- docker-compose.yml
This pull request introduces a Docker Compose configuration to streamline the process of building and starting Tabler in a Docker environment locally. 
. A new docker-compose.yml file has been added to the repository.
. The README file has been updated to include instructions on how to use Docker Compose to build and start Tabler.
> Introduce Docker Compose Config to build and run tabler locally

- src/scss/_variables.scss
- src/scss/ui/_forms.scss
This PR aims to resolve the issue mentioned in #1768 
Steps taken to resolve the issue:
- I created a new variable called $form-secondary-color which would allow us to have a globally initialzed secondary color value for the forms.scss file. 
- I also declared this variable to be equal to the gray-500 as it was the value for the previous variable(var(--#{$prefix}secondary)). 
- I replaced the definition of var(--#{$prefix}secondary) to var(--#{$prefix}gray-500) in the _variables.scss file. 
- I noticed that on local developmental environment, some of the colours are being taken from the demo\dist\css\tabler.css file and I was wondering whether I should change the definition within this file. As based on my understanding, this file is used to deploy a specific version of the application …
> Fix for #1768 - Use of secondary color in certain form element

- src/scss/ui/_ribbons.scss
This PR fixes issue #1923 
WHAT DOES THIS PR DO?
It solves the issue of incorrect borders in the ribbon-start class as mentioned in the issue.
> Fixes #1923: Added correct borders to the ribbon start class

- src/scss/_utilities.scss
This fix was needed because in dark mode the border color of these utility classes was not changing to its dark mode equivalent.
> FIX: ensure border color works in dark mode

- .changeset/old-paws-float.md
- src/scss/ui/_type.scss
Padding removed from `<code>` inside  `<pre>`
> Fix padding in code blocks

- .changeset/sixty-spoons-move.md
- src/scss/ui/_type.scss
`max-width` removed from `<svg/>` element
fixes #1977
> Fix cells with inline icons

- .changeset/nine-lions-smell.md
- src/scss/vendor/_tom-select.scss
Fix to prevent overlapping by buttons.
Before change:  
After change:
> Increase z-index of ts-dropdown 

- .changeset/small-avocados-end.md
- src/scss/_variables.scss
Before change:  
After change:  
Fixes #1890
> Increase contrast of active dropdown-item in vertical layout

- .changeset/webfont-unpkg.md
- src/pages/_includes/layout/css.html
https://www.unpkg.com/@tabler/icons-webfont@latest/dist/tabler-icons.min.css used instead of https://cdn.statically.io/gh/tabler/tabler-icons/master/iconfont/tabler-icons.min.css
> Fix link to webfont icons

- .changeset/popular-news-sell.md
- src/pages/_data/menu.yml
- src/scss/ui/_type.scss
\+ Remove icon from pagination menu item.
Fixes #1836
> Remove text-decoration on hovering a element with child having an icon class

- .changeset/perfect-trainers-rush.md
- src/pages/search-results.html
Fixes #1870
Before changes:  
After changes:
> Fix layout of search results for small and medium screens

- .changeset/light-beers-study.md
- src/pages/alerts.html
The previous description was copied from "Dismissible alerts"
Fixes #1844
> Fix description of alerts with a description

- .changeset/sixty-windows-tickle.md
- src/scss/ui/_nav.scss
Fixes #1522
Before fix:  
After fix:
> Fix color of disabled nav-link in nav-bordered

- src/pages/_includes/marketing/sections/testimonials.html
- src/scss/_variables.scss
- src/scss/marketing/_pricing.scss
Maybe we should change the border for pricing cards on dark mode too, or does this look good?
> Make marketing pages fully support dark mode

- .gitignore
- package.json
Added missing **"start"** alias in the scripts section of the _package.json_ file to allow the command: 
```bash
pnpm run start
```
to work as per documentation.
Added "pnpm-lock.yaml" to ".gitignore" to remove conflict as suggested in #2123
> added "start" command to package.json scripts as alias for dev

- .changeset/tidy-hairs-wonder.md
- core/scss/ui/_cards.scss
This PR adds a missing `border-radius` to the `.card-header-tabs` class to match the style applied to `.card-header:first-child`. This ensures visual consistency across card headers that use tabs.
Without this fix, `.card-header-tabs` has sharp corners, which breaks the rounded card appearance and leads to inconsistent UI.
Let me know if this should be applied in a different place or if there's a related variable that should be used instead.
First-time contributor — thanks for the awesome work on Tabler!
> fix: add missing border-radius to .card-header-tabs

- shared/includes/cards/carousel.html
It seems that previously a prop was not being passed to the relevant carousel include file to enable captions for that specific example.
> Fix carousel with captions demo on preview website

- .changeset/short-hounds-promise.md
- docs/content/icons/libraries/webfont.md
Since the install guides for other Tabler libraries use the tabs-package for showing the steps, it would appear to make sense to use it for the webfont install guide also.
> Use tabs-package include to show webfont install steps

- .changeset/silent-hornets-appear.md
- docs/content/ui/components/tables.md
Previously, the example in the documentation for sticky header tables did not actually show the sticky header behaviour, since the table was not scrollable. This update increases the number of rows in the table and forces the table's wrapper to have a specific height, causing the table to become scrollable and thus demonstrating the sticky header behaviour.
~~I'm not 100% sure that it is enough to add a height prop to the include statement at the bottom of the file here, as I am still not sure how to access a local copy of the documentation app to test it (since the docs link on the development build of the preview site leads to the _production_ documentation site). Hopefully this fix is correct though.~~ Figured out how to access documentation in development. This fix appears to be …
> Demonstrate sticky header table more clearly in docs

- docs/content/ui/components/carousel.md
It might be more helpful to explain on the carousel with captions example that the code given will hide the captions on small screens. (Partly for the case where people might already be browsing the documentation on a mobile device)
> Add note to carousel with captions example

- .changeset/dry-spiders-double.md
- docs/content/ui/forms/form-input-mask.md
There was a missing lib that needed to be added to the front-matter of the form input mask documentation page.
Fixes #2308
> Fix input mask example in docs

- .changeset/short-balloons-smile.md
- docs/content/ui/forms/form-elements.md
The example of an input with an appended `<kbd>` previously had a change introduced in https://github.com/tabler/tabler/pull/1492 to its label that was incorrect. 
This commit brings it back to what it was originally, as first written in https://github.com/tabler/tabler/pull/1391.
Before this change:
After this change:
> Fix incorrect label text on form elements docs page

- docs/content/ui/forms/form-elements.md
Previously, the section heading for 'Input with appended `<kbd>`' was not appearing on that page's table of contents. This was due to how the headings on pages were parsed when constructing the TOC.
This change updates the heading. It seems reasonable to simplify the heading, rather than modify the code that constructs the TOC.
Before this change:
After this change:
> Add missing TOC item on the preview's form elements page

- .changeset/eleven-seals-unite.md
- docs/content/ui/components/avatars.md
- docs/content/ui/components/buttons.md
- docs/content/ui/components/countup.md
- docs/content/ui/components/divider.md
- docs/content/ui/components/icons.md
- docs/content/ui/components/progress.md
- docs/content/ui/components/range-slider.md
- docs/content/ui/components/ribbons.md
- docs/content/ui/components/spinners.md
- docs/content/ui/components/statuses.md
- docs/content/ui/components/steps.md
- docs/content/ui/forms/form-color-check.md
- docs/content/ui/forms/form-image-check.md
- docs/content/ui/getting-started/how-to-contribute.md
- docs/content/ui/getting-started/installation.md
Previously, a change was made in this commit:
https://github.com/tabler/tabler/commit/88b9e87c6ed17c34911f6b09ddc00439bb4a6ab4
..that broke several links. This change corrects this. Additionally, several other links have had their labels updated to make them more easily understood at a glance/easier to 'scan', by replacing the use of text such as 'click here' with more descriptive text.
> Improve several link labels

- .changeset/strong-frogs-brush.md
- docs/eleventy.config.mjs
> Fix: Exclude headings inside `.example` from the Table of Contents

- .changeset/poor-spoons-deny.md
- shared/includes/docs/colors.html
Previously, a fixed padding amount was causing the colour swatches to overlap each other on small screens. They are now responsive: on small screens, they shrink slightly and spread out more across each line of their layout.
The markup was also changed slightly to make use of the `row-cols-*` shortcuts.
Fixes #2327.
> Fix colour swatches on small screens

- .changeset/fresh-ways-begin.md
- docs/content/emails/introduction/contents.md
- docs/content/ui/components/icons.md
- docs/content/ui/forms/form-elements.md
- docs/content/ui/getting-started/how-to-contribute.md
- The links to the email 'compiled-html' and 'source-html' documentation pages were broken.
- Fixed an updated link label that was accidentally overwritten during a previous merge conflict resolution.
- Changed references to 'npm' in 'how to contribute' docs to 'pnpm' and reworded things slightly for better readability.
- Added notes to 'how to contribute' docs about viewing local copies of both the preview site _and_ the documentation site
- Changed outdated source folder references in 'how to contribute' docs
- Remove some empty divs on the form elements page's range sliders example
> Add a few small documentation fixes and updates

- .changeset/stale-cherries-draw.md
- docs/eleventy.config.mjs
- shared/includes/docs/example.html
Previous fix omitted the examples where any `<div>` was closed before the headings.
Added additional classes in the Regex expression.
Closes #2291
> Fix: Exclude headings in the carousel and modal examples from ToC

- .changeset/grumpy-bobcats-kick.md
- docs/scss/docs.scss
Fixes #2376 (copy button will be added in https://github.com/tabler/tabler/pull/2378)
Selection of code block changed from:  
to:
> Use primary color for `::selection` inside `<code>` in docs

- .changeset/giant-ligers-joke.md
- preview/pages/marketing/real-estate.html
- shared/includes/marketing/hero/side.html
- shared/includes/marketing/sections/companies.html
- shared/includes/marketing/sections/faq.html
- shared/includes/marketing/sections/features-2.html
- shared/includes/marketing/sections/features-3.html
- shared/includes/marketing/sections/testimonials.html
- shared/layouts/marketing.html
Some rows on the marketing site had non-responsive gutters, causing a horizontal overflow on mobiles. They are now made responsive.
> Prevent some marketing site rows overflowing on mobile

- .changeset/smart-apples-glow.md
- core/scss/ui/_lists.scss
In "Last commits" example (https://preview.tabler.io/lists.html) there is example with classes "list-group list-group-flush list-group-hoverable" but the fact is that "list-group-hoverable" is ignored and items are hoverable even without that.
> List group item hoverable only with .list-group-hoverable class

- .changeset/brave-books-listen.md
- core/scss/_variables.scss
This PR corrects the line height setups for `.btn-sm` and `.btn-lg` which should fix #2258.
> fix: use relative line heights to make calculations work (#2258)
